version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /goldrun-windows
    schedule:
      interval: monthly

  - package-ecosystem: cargo
    directory: /goldrun-windows/src-tauri
    schedule:
      interval: monthly
